### ISSUE TITLE
What is this trying to solve?

### ISSUE THREAD

**Issue by kamushadenes** [hc0d3r/nopasswd-scan#1]
Hello, 

First of all, thanks for your code. It is a good idea trying to enumerate possible commands.

That said, I was wondering what this project is trying to accomplish.

From the sudo manpage:

```    
 -l, --list  If no command is specified, list the allowed (and forbidden) commands for the invoking user (or the user specified by the -U option) on the current host.  A longer list format is used if
                 this option is specified multiple times and the security policy supports a verbose output format.

                 If a command is specified and is permitted by the security policy, the fully-qualified path to the command is displayed along with any command line arguments.  If a command is specified
                 but not allowed by the policy, sudo will exit with a status value of 1.
```

`sudo -l` should display all allowed commands of the calling user, is there any case where that doesn't apply?

**Comment by hc0d3r** [comment]
Good question, when I made the code I didn't even remember that option, lmao. Excluding edit the sudo source code and compile it without this option, I have no idea if there is a way to block this.

**Comment by hc0d3r** [comment]
~un~fortunately, there is a way to block this, using listpw:
```
Defaults listpw=all
```
I tested here, and the scan can bypass this, I was starting to think I had programmed something useless again.
